image: mcr.microsoft.com/dotnet/core/sdk:3.1
stages:
    - build
    - test
    - publish
    - cleanup

variables:
        solution: "Traktor.sln"
        version: "1.${CI_PIPELINE_ID}"
        nuget_url: https://api.nuget.org/v3/index.json

build:
    stage: build
    only:
        - master
    artifacts:
        paths:
            - publish/
    script:
            - mkdir publish/
            - dotnet restore
            - dotnet build /p:Version=$version -c Release  --no-restore
            - dotnet pack  /p:Version=$version -c Release --no-restore --no-build -o ../publish
            - cp /builds/sstockha/publish/* publish/

publish:
    stage: publish
    only:
        - master
    script:
            - dotnet nuget push publish/*${CI_PIPELINE_ID}*.nupkg --source $nuget_url --api-key $NUGET_API_KEY --skip-duplicate

cleanup:
    stage: cleanup
    only:
        - master
    script:
            - rm publish/*${CI_PIPELINE_ID}*.nupkg
