image: mcr.microsoft.com/dotnet/core/sdk:2.2.301

stages:
    - build
    - test
    - publish

variables:
        solution: "Traktor.sln"
        version: "1.0"

build:
    stage: build
    only:
        - master
    artifacts:
        paths:
            - publish/
    script:
            - dotnet restore
            - dotnet build /p:Version=$version -c Release  --no-restore
            - dotnet pack  /p:Version=$Version -c Release --no-restore --no-build -o ../publish

